# Generated by Django 4.1.7 on 2023-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storie',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/cover'),
        ),
        migrations.AddField(
            model_name='storie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images'),
        ),
    ]
