# Generated by Django 4.1.7 on 2023-03-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testikt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testIkt',
        ),
    ]
