# Generated by Django 4.1.7 on 2023-03-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_testikt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
