# Generated by Django 4.1.7 on 2023-03-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Story',
            new_name='Storie',
        ),
    ]
