# Generated by Django 4.1.7 on 2023-03-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_rename_category_categorie_rename_story_storie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storie',
            name='cover_image',
            field=models.ImageField(upload_to='stories/cover'),
        ),
        migrations.AlterField(
            model_name='storie',
            name='image',
            field=models.ImageField(upload_to='stories/images'),
        ),
        migrations.AlterField(
            model_name='storie',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='story', to='home.tag'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('incomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomments', to='home.comment')),
                ('storie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='home.storie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
