# Generated by Django 4.1.7 on 2023-03-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_storie_cover_image_alter_storie_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
